##web sources

source("Code/Functions.R")

# collected 2019_11_11
w1 <- read_html("http://www.lynxuk.org/")
w2 <- read_html("https://www.nationalgeographic.co.uk/environment-and-conservation/2019/09/lynx-and-wolf-may-soon-be-roaming-britains-wild-places-again")
w3 <- read_html("https://scottishwildlifetrust.org.uk/2019/07/could-we-reintroduce-lynx-to-scotland/")
w4 <- read_html("https://www.rewildingbritain.org.uk/rewilding/reintroductions/lynx")
w5 <- read_html("https://www.theguardian.com/environment/2019/may/21/plan-to-return-lynx-to-uk-receives-fresh-boost")
w6 <- read_html("https://www.sciencedaily.com/releases/2019/03/190329134750.htm")
w7 <- read_html("https://www.scottishfield.co.uk/outdoors/wildlifeandconservation/the-missing-lynx-should-it-be-reintroduced/")
w8 <- read_html("https://www.gov.uk/government/publications/lynx-reintroduction-in-kielder-forest")
w9 <- read_html("https://www.dailymail.co.uk/sciencetech/article-6705921/Wild-lynx-reintroduced-Britain-1-000-years.html")
w10 <- read_html("https://www.scitecheuropa.eu/call-for-the-reintroduction-of-the-lynx-in-the-uk/96522/")
w11 <- read_html("https://www.nfuonline.com/news/latest-news/lynx-reintroduction-raises-livestock-and-biodiversity-concerns/")
w12 <- read_html("https://stv.tv/news/scotland/1437651-could-wild-lynx-make-a-return-to-scotland-s-forests/")
w13 <- read_html("https://www.telegraph.co.uk/news/2019/03/29/lynx-would-spread-across-highlands-within-century-reintroduced/")
w14 <- read_html("https://www.fwi.co.uk/news/environment/environmental-issues-wildlife/scotland-is-best-uk-location-for-lynx-reintroduction-says-ecologist")
w15 <- read_html("https://www.countrysideonline.co.uk/food-and-farming/protecting-the-environment/rewilding-lynx-beavers-and-wild-boar/")
w16 <- read_html("https://www.hutton.ac.uk/research/projects/reintroduction-lynx")
w17 <- read_html("https://www.dailyrecord.co.uk/news/scottish-news/wild-lynx-cats-reintroduced-trial-14002811")
w18 <- read_html("https://www.stir.ac.uk/news/2019/03/new-study-models-the-proposed-reintroduction-of-the-eurasian-lynx-to-scotland/")
w19 <- read_html("https://www.bbc.co.uk/news/uk-england-tyne-46446890")
w20 <- read_html("https://www.gwct.org.uk/lynx-reintroduction-free-guide/")

w1 <- web_scrape(w1, "div :nth-child(2)")
w2 <- web_scrape(w2, "div")
w3 <- web_scrape(w3, ".main-width , strong")
w4 <- web_scrape(w4, ".content")
w5 <- web_scrape(w5, "p")
w6 <- web_scrape(w6, ".col-md-push-4")
w7 <- web_scrape(w7, ".lightbox-content")
w8 <- web_scrape(w8, ".responsive-bottom-margin")
w9 <- web_scrape(w9, ".imageCaption , .mol-para-with-font , .mol-bullets-with-font , h2")
w10 <- web_scrape(w10, "h2 , p")
w11 <- web_scrape(w11, ".HtmlHelper-NgageContent")
w12 <- web_scrape(w12, ".article__content")
w13 <- web_scrape(w13, ".js-article")
w14 <- web_scrape(w14, ".single-title , p , ul , h2")
w15 <- web_scrape(w15, ".py-4")
w16 <- web_scrape(w16, "#column-left")
w17 <- web_scrape(w17, ".sub-title , .publication-font , .article-body")
w18 <- web_scrape(w18, ".c-testimonial__quote , .small-12")
w19 <- web_scrape(w19, ".story-body")
w20 <- web_scrape(w20, ".container")

w1 <- trim_web(w1)
w2 <- trim_web(w2)
w3 <- trim_web(w3)
w4 <- trim_web(w4)
w5 <- trim_web(w5)
w6 <- trim_web(w6)
w7 <- trim_web(w7)
w8 <- trim_web(w8)
w9 <- trim_web(w9)
w10 <- trim_web(w10)
w11 <- trim_web(w11)
w12 <- trim_web(w12)
w13 <- trim_web(w13)
w14 <- trim_web(w14)
w15 <- trim_web(w15)
w16 <- trim_web(w16)
w17 <- trim_web(w17)
w18 <- trim_web(w18)
w19 <- trim_web(w19)
w20 <- trim_web(w20)


w1 <- w1 %>% unnest_tokens(word, text) 
w2 <- w2 %>% unnest_tokens(word, text) 
w3 <- w3 %>% unnest_tokens(word, text) 
w4 <- w4 %>% unnest_tokens(word, text) 
w5 <- w5 %>% unnest_tokens(word, text) 
w6 <- w6 %>% unnest_tokens(word, text) 
w7 <- w7 %>% unnest_tokens(word, text) 
w8 <- w8 %>% unnest_tokens(word, text) 
w9 <- w9 %>% unnest_tokens(word, text) 
w10 <- w10 %>% unnest_tokens(word, text) 
w11 <- w11 %>% unnest_tokens(word, text) 
w12 <- w12 %>% unnest_tokens(word, text) 
w13 <- w13 %>% unnest_tokens(word, text) 
w14 <- w14 %>% unnest_tokens(word, text) 
w15 <- w15 %>% unnest_tokens(word, text) 
w16 <- w16 %>% unnest_tokens(word, text) 
w17 <- w17 %>% unnest_tokens(word, text) 
w18 <- w18 %>% unnest_tokens(word, text) 
w19 <- w19 %>% unnest_tokens(word, text) 
w20 <- w20 %>% unnest_tokens(word, text) 
